### ISSUE TITLE
Selenium not identifying elements in IE11 browser

### ISSUE THREAD

**Issue by YugandharBandari** [lukeis/selenium-gcode-issue-archive#8842]
Hi Team,

Selenium not identifying elements in IE11 browser. note same scripts are workingf ine with Chrome and Firefox

Here is the details :

Selenium : 3.7
Browser : IE11
Operating System : Windows 64 but using IEDRIVERSERVER 32 bit to improve speed

Adjusted Browser zones security settings and also did the registry settings.

Trace log details :

Started InternetExplorerDriver server (32-bit)
3.7.0.0
Listening on port 4413
Only local connections are allowed
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: All firstMatch elements failed validation
Invalid capabilities in firstMatch element 0: unhandledPromptBehavior is type boolean instead of string
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'OTSWIT4FDHVF27L', ip: '100.117.233.120', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: InternetExplorerDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:223)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:215)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:160)
	at tempjava.ie11.main(ie11.java:33)

**Comment by YugandharBandari** [comment]
package tempjava;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class ie11 {
	
	public static void main(String[] args) {
		
		
	
		DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
		
		capabilities.setCapability(CapabilityType.BROWSER_NAME, "internet explorer");
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		capabilities.setJavascriptEnabled(true);
		capabilities.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING,true);
		capabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
		capabilities.setCapability(InternetExplorerDriver.FORCE_CREATE_PROCESS, true); 
		//capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true); 
		capabilities.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true); 
		capabilities.setCapability("ignoreProtectedModeSettings", true);
		capabilities.setCapability("nativeEvents", false);
		capabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, false);
		capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, true);
				
		System.setProperty("webdriver.ie.driver", "C:\\selenium-java-3.7.1\\IEDriverServer.exe");
		
		@SuppressWarnings("deprecation")
		WebDriver driver = new InternetExplorerDriver(capabilities);
		
		
		
		driver.manage().window().maximize();

		
				
		//InternetExplorerDriver  driver = new InternetExplorerDriver();
			 driver.navigate().refresh();
			 driver.navigate().to("http://google.com");
			 
			 driver.findElement(By.xpath(".//*[@id='gs_htif0']")).sendKeys("Selenium");
			 
			 driver.findElement(By.xpath(".//*[@id='tsf']/div[2]/div[3]/center/input[1]")).click();
			 
			 driver.quit();

		}
	}
