### ISSUE TITLE
Extent report generation problem

### ISSUE THREAD

**Issue by shrikantMarkad** [lukeis/selenium-gcode-issue-archive#8850]
These are the errors after running as a testng test
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:220)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

CODE
package com.skm.extendreportprogram;

import java.io.File;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.AfterClass;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

import library.Utility;

public class ExtendreportDemo
{

	
	ExtentReports report;
	ExtentTest logger;
	WebDriver driver;
	
	@Test
	public void test_Extent()
	{
		
		report=new ExtentReports("D:\\report\\outputfile.html",true);
		logger=report.startTest("test_Extent");
		driver=new FirefoxDriver();
		//logger.log(LogStatus.INFO,"Browser started");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(8, TimeUnit.SECONDS);
		//logger.log(LogStatus.INFO,"Browser maximized");
		driver.get("C:\\Users\\lenovo pc\\Desktop\\javabykiran\\Offline Website\\pages\\examples\\login.html");
		driver.findElement(By.id("email")).sendKeys("kiran@gmail.com");
		driver.findElement(By.id("password")).sendKeys("123456");
		driver.findElement(By.xpath(".//*[@id='form']/div[3]/div/button")).click();
		//logger.log(LogStatus.INFO,"Application loaded");
		String title=driver.getTitle();
		System.out.println(title);
		Assert.assertTrue(title.contains("Admin"));
		
		logger.log(LogStatus.PASS,"Title of the page is verified");
		report.endTest(logger);
		report.flush();
			
	}
	
	@AfterClass
	public void test_Failure_function(ITestResult result) throws Exception
	{
		if(result.getStatus()==ITestResult.FAILURE)
		{
			String capturefilepath=Utility.screenshot(driver, result.getName());
			String imagepath=logger.addScreenCapture(capturefilepath);
			logger.log(LogStatus.FAIL,"Title verification",imagepath);
		}
		
		report.endTest(logger);
		report.flush();
		report.close();
		
		driver.get("D:\\report\\outputfile.html");
	}
	
	
}

Screenshot code

package library;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;

public class Utility 
{
	public static String screenshot(WebDriver driver,String screenshotname)
	{
		try 
		{
			TakesScreenshot take=(TakesScreenshot)driver;
			File source=take.getScreenshotAs(OutputType.FILE);
			String destination="D:\\report\\"+screenshotname+".png";
			File dest=new File(destination);
			FileUtils.copyFile(source,dest);
			System.out.println("screenshot taken with name:::::::"+screenshotname);
			return destination;
		} 
		catch (Exception e) 
		{
			System.out.println("screenshot not taken"+e.getMessage());
			return e.getMessage();
		}
	}
}

**Comment by barancev** [comment]
The exception is not related to Selenium, it seems to be a TestNG issue.
